In [2]:
import numpy as np
a=np.array([-1,1]) 

b=np.array([1,1]) 

np.dot(a,b) 

0

In [18]:
a=np.array([0,1,0,1,0]) 

b=np.array([1,0,1,0,1]) 

a*b 

array([0, 0, 0, 0, 0])

In [19]:
a=np.array([1,1,1,1,1]) 

a+1

array([2, 2, 2, 2, 2])

In [17]:
class Rectangle(object): 

    def __init__(self,width=2,height =3,color='r'):

        self.height=height 

        self.width=width 

        self.color=color 

    def drawRectangle(self): 

        import matplotlib.pyplot as plt 

        plt.gca().add_patch(plt.Rectangle((0, 0),self.width, self.height ,fc=self.color)) 

        plt.axis('scaled') 
        plt.show()

NameError: name 'plt' is not defined

In [14]:
'1:2,3:4'.split(':')

['1', '2,3', '4']

In [13]:
dict = {
    "name":"Jose",
    "name":"Anne"
}
dict

{'name': 'Anne'}

In [4]:
X=np.array([[1,0],[0,1]]) 

Y=np.array([[0,1],[1,0]]) 

Z=X+Y 
print(Z)

[[1 1]
 [1 1]]


In [6]:
X=np.array([[1,0,1],[2,2,2]]) 

out=X[0:2,2]
print(out)

[1 2]


In [7]:
X=np.array([[1,0],[0,1]])

Y=np.array([[2,2],[2,2]]) 

Z=np.dot(X,Y) 
print(Z)

[[2 2]
 [2 2]]


In [8]:
%ls

 Volume in drive C has no label.
 Volume Serial Number is 523E-18D4

 Directory of C:\Users\USER

04/15/2024  05:07 PM    <DIR>          ${test.tmp.dir}
05/02/2024  12:28 AM    <DIR>          %TEMP%
05/31/2024  10:48 AM    <DIR>          .
05/31/2024  10:48 AM    <DIR>          ..
02/04/2024  02:08 PM    <DIR>          .anaconda
05/18/2024  08:47 PM    <DIR>          .aws
05/27/2024  01:05 PM            30,672 .bash_history
04/13/2024  12:18 AM    <DIR>          .cache
02/16/2024  08:58 PM    <DIR>          .cassandra
04/16/2024  07:51 PM    <DIR>          .conda
02/04/2024  02:51 PM                25 .condarc
02/04/2024  02:07 PM    <DIR>          .continuum
03/07/2024  12:42 AM    <DIR>          .cvlib
04/13/2024  12:23 AM    <DIR>          .eclipse
05/24/2024  09:08 PM               218 .gitconfig
05/16/2024  03:04 PM                53 .git-for-windows-updater
05/02/2024  03:36 PM               571 .hivehistory
05/25/2024  02:57 AM    <DIR>          .ipynb_checkpoints
02/04/2024  02

In [11]:
%%bash
touch example.txt
echo "This is line 1

This is line 2

This is line 3" >> example.txt

In [12]:
with open("Example.txt","r") as file1: 

     file_stuff=file1.readline() 


print(file_stuff)

This is line 1



In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\USER\Desktop\ALL MY TASKS\TSI DATA SCIENCE\Datasets\CSV Datasets\insurance.csv")
df.head(10)

Unnamed: 0  age     sex     bmi  children smoker     region      charges
0           0   19  female  27.900         0    yes  southwest  16884.92400
1           1   18    male  33.770         1     no  southeast   1725.55230
2           2   28    male  33.000         3     no  southeast   4449.46200
3           3   33    male  22.705         0     no  northwest  21984.47061
4           4   32    male  28.880         0     no  northwest   3866.85520
5           5   31  female  25.740         0     no  southeast   3756.62160
6           6   46  female  33.440         1     no  southeast   8240.58960
7           7   37  female  27.740         3     no  northwest   7281.50560
8           8   37    male  29.830         2     no  northeast   6406.41070
9           9   60  female  25.840         0     no  northwest  28923.13692

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1338 non-null   int64  
 1   age         1338 non-null   int64  
 2   sex         1338 non-null   object 
 3   bmi         1338 non-null   float64
 4   children    1338 non-null   int64  
 5   smoker      1338 non-null   object 
 6   region      1338 non-null   object 
 7   charges     1338 non-null   float64
dtypes: float64(2), int64(3), object(3)
memory usage: 83.8+ KB


In [4]:
df.region.unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [3]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
from statsmodels.multivariate.manova import MANOVA

In [9]:
# One-Way ANOVA
#testing the effect of region on charges.
model_anova_one_way = ols('charges ~ C(region)', data=df).fit()
anova_results_one_way = anova_lm(model_anova_one_way)
print(anova_results_one_way)

print("*****************")
print("*****************")
print("*****************")
# Two-Way ANOVA
#test the effect of region and smoker on charges
model_anova_two_way = ols('charges ~ C(region) + C(smoker)', data=df).fit()
anova_results_two_way = anova_lm(model_anova_two_way)
print(anova_results_two_way)

print("*****************")
print("*****************")
print("*****************")

# N-Way ANOVA
#test the effect of region, smoker, and sex on charges.
model_anova_n_way = ols('charges ~ C(region) + C(smoker) + C(sex)', data=df).fit()
anova_results_n_way = anova_lm(model_anova_n_way)
print(anova_results_n_way)
print("*****************")
print("*****************")
print("*****************")

# Two-Way ANOVA with Interaction
#test the interaction between region and smoker
model_anova_two_way_interaction = ols('charges ~ C(region) * C(smoker)', data=df).fit()
anova_results_two_way_interaction = anova_lm(model_anova_two_way_interaction)
print(anova_results_two_way_interaction)

               df        sum_sq       mean_sq         F    PR(>F)
C(region)     3.0  1.300760e+09  4.335866e+08  2.969627  0.030893
Residual   1334.0  1.947735e+11  1.460071e+08       NaN       NaN
*****************
*****************
*****************
               df        sum_sq       mean_sq            F         PR(>F)
C(region)     3.0  1.300760e+09  4.335866e+08     7.763543   3.852482e-05
C(smoker)     1.0  1.203267e+11  1.203267e+11  2154.497688  1.141794e-280
Residual   1333.0  7.444679e+10  5.584906e+07          NaN            NaN
*****************
*****************
*****************
               df        sum_sq       mean_sq            F         PR(>F)
C(region)     3.0  1.300760e+09  4.335866e+08     7.757896   3.883674e-05
C(smoker)     1.0  1.203267e+11  1.203267e+11  2152.930530  1.830264e-280
C(sex)        1.0  1.698505e+06  1.698505e+06     0.030390   8.616341e-01
Residual   1332.0  7.444510e+10  5.588971e+07          NaN            NaN
*****************
**********

In [11]:
#ANCOVA combines ANOVA and regression to evaluate whether population means of a 
#dependent variable (e.g., charges) are equal across levels of a categorical independent 
#variable (e.g., region), while controlling for the effects of one or more continuous 
#covariates (e.g., age, bmi).

#Testing the effect of region on charges, controlling for age:
    # One-Way ANCOVA
model_ancova_one_way = ols('charges ~ C(region) + age', data=df).fit()
ancova_results_one_way = anova_lm(model_ancova_one_way)
print(ancova_results_one_way)

# Two-Way ANCOVA
#Testing the effect of region and smoker on charges, controlling for age:
model_ancova_two_way = ols('charges ~ C(region) + C(smoker) + age', data=df).fit()
ancova_results_two_way = anova_lm(model_ancova_two_way)
print(ancova_results_two_way)

# N-Way ANCOVA
#Testing the effect of region, smoker, and sex on charges, controlling for age and bmi:
model_ancova_n_way = ols('charges ~ C(region) + C(smoker) + C(sex) + age + bmi', data=df).fit()
ancova_results_n_way = anova_lm(model_ancova_n_way)
print(ancova_results_n_way)

# Two-Way ANCOVA with Interaction
#Testing the interaction effect between region and smoker on charges, controlling for age:
model_ancova_two_way_interaction = ols('charges ~ C(region) * C(smoker) + age', data=df).fit()
ancova_results_two_way_interaction = anova_lm(model_ancova_two_way_interaction)
print(ancova_results_two_way_interaction)


               df        sum_sq       mean_sq           F        PR(>F)
C(region)     3.0  1.300760e+09  4.335866e+08    3.262960  2.075098e-02
age           1.0  1.764263e+10  1.764263e+10  132.769766  2.366932e-29
Residual   1333.0  1.771308e+11  1.328813e+08         NaN           NaN
               df        sum_sq       mean_sq            F        PR(>F)
C(region)     3.0  1.300760e+09  4.335866e+08    10.599409  6.879275e-07
C(smoker)     1.0  1.203267e+11  1.203267e+11  2941.492332  0.000000e+00
age           1.0  1.995911e+10  1.995911e+10   487.918072  2.238023e-92
Residual   1332.0  5.448769e+10  4.090667e+07          NaN           NaN
               df        sum_sq       mean_sq            F         PR(>F)
C(region)     3.0  1.300760e+09  4.335866e+08    11.702604   1.433545e-07
C(smoker)     1.0  1.203267e+11  1.203267e+11  3247.645132   0.000000e+00
C(sex)        1.0  1.698505e+06  1.698505e+06     0.045843   8.304942e-01
age           1.0  1.995928e+10  1.995928e+10   538

In [12]:
#MANOVA is used when there are multiple dependent variables. In this case, let's consider charges 
#and bmi as our dependent variables and region, smoker, and sex as our independent variables.

# One-Way MANOVA
#Testing the effect of region on charges and bmi
manova_one_way = MANOVA.from_formula('charges + bmi ~ C(region)', data=df)
manova_results_one_way = manova_one_way.mv_test()
print(manova_results_one_way)

# Two-Way MANOVA
#Testing the effect of region and smoker on charges and bmi
manova_two_way = MANOVA.from_formula('charges + bmi ~ C(region) + C(smoker)', data=df)
manova_results_two_way = manova_two_way.mv_test()
print(manova_results_two_way)

# N-Way MANOVA
#Testing the effect of region, smoker, and sex on charges and bmi:
manova_n_way = MANOVA.from_formula('charges + bmi ~ C(region) + C(smoker) + C(sex)', data=df)
manova_results_n_way = manova_n_way.mv_test()
print(manova_results_n_way)

# Two-Way MANOVA with Interaction
#Testing the interaction effect between region and smoker on charges and bmi:
manova_two_way_interaction = MANOVA.from_formula('charges + bmi ~ C(region) * C(smoker)', data=df)
manova_results_two_way_interaction = manova_two_way_interaction.mv_test()
print(manova_results_two_way_interaction)

                   Multivariate linear model
                                                                
----------------------------------------------------------------
       Intercept        Value  Num DF   Den DF   F Value  Pr > F
----------------------------------------------------------------
          Wilks' lambda 0.1419 2.0000 1333.0000 4029.6054 0.0000
         Pillai's trace 0.8581 2.0000 1333.0000 4029.6054 0.0000
 Hotelling-Lawley trace 6.0459 2.0000 1333.0000 4029.6054 0.0000
    Roy's greatest root 6.0459 2.0000 1333.0000 4029.6054 0.0000
----------------------------------------------------------------
                                                                
----------------------------------------------------------------
         C(region)        Value  Num DF   Den DF  F Value Pr > F
----------------------------------------------------------------
            Wilks' lambda 0.9159 6.0000 2666.0000 19.9495 0.0000
           Pillai's trace 0.0843 6.0000 2668.

In [13]:
#MANCOVA is used when there are multiple dependent variables, and you want to control 
#for the effects of one or more covariates.

# One-Way MANCOVA
#Testing the effect of region on charges and bmi, controlling for age
mancova_one_way = MANOVA.from_formula('charges + bmi ~ C(region) + age', data=df)
mancova_results_one_way = mancova_one_way.mv_test()
print(mancova_results_one_way)

# Two-Way MANCOVA
#Testing the effect of region and smoker on charges and bmi, controlling for age:
mancova_two_way = MANOVA.from_formula('charges + bmi ~ C(region) + C(smoker) + age', data=df)
mancova_results_two_way = mancova_two_way.mv_test()
print(mancova_results_two_way)

# N-Way MANCOVA
#Testing the effect of region, smoker, and sex on charges and bmi, controlling for age and children:
mancova_n_way = MANOVA.from_formula('charges + bmi ~ C(region) + C(smoker) + C(sex) + age + children', data=df)
mancova_results_n_way = mancova_n_way.mv_test()
print(mancova_results_n_way)

# Two-Way MANCOVA with Interaction
#Testing the interaction effect between region and smoker on charges and bmi, controlling for age:
mancova_two_way_interaction = MANOVA.from_formula('charges + bmi ~ C(region) * C(smoker) + age', data=df)
mancova_results_two_way_interaction = mancova_two_way_interaction.mv_test()
print(mancova_results_two_way_interaction)


                   Multivariate linear model
                                                                
----------------------------------------------------------------
       Intercept        Value  Num DF   Den DF   F Value  Pr > F
----------------------------------------------------------------
          Wilks' lambda 0.3487 2.0000 1332.0000 1244.1862 0.0000
         Pillai's trace 0.6513 2.0000 1332.0000 1244.1862 0.0000
 Hotelling-Lawley trace 1.8681 2.0000 1332.0000 1244.1862 0.0000
    Roy's greatest root 1.8681 2.0000 1332.0000 1244.1862 0.0000
----------------------------------------------------------------
                                                                
----------------------------------------------------------------
         C(region)        Value  Num DF   Den DF  F Value Pr > F
----------------------------------------------------------------
            Wilks' lambda 0.9136 6.0000 2664.0000 20.5231 0.0000
           Pillai's trace 0.0867 6.0000 2666.

In [ ]:
# #Interpreting the results
# ANOVA: The p-value for the Group variable is greater than 0.05, 
#indicating that there is no statistically significant difference in Y1 across the different groups.

# ANCOVA: The p-value for the Group variable less than 0.05, indicating that there 
#is a statistically significant difference in Y1 across the different groups when controlling for Covariate. 
#The covariate itself is highly significant (p < 0.001).

# MANOVA: The test indicates significant differences across the groups for the combination of Y1 and Y2 
#(all p-values < 0.001).

# MANCOVA: The test indicates significant differences across the groups for the combination of Y1 and Y2 
#when controlling for Covariate (all p-values < 0.001). The covariate also has a significant effect 
#on the combination of Y1 and Y2 (p < 0.001).